quarkus.http.port=8080
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=motion
kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.motion_event.connector=smallrye-kafka
mp.messaging.outgoing.motion_event.topic=motion_event

mp.messaging.incoming.motion-event-in.connector=smallrye-kafka
mp.messaging.incoming.motion-event-in.topic=motion_event
mp.messaging.incoming.motion-event-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.motion-event-in.auto.offset.reset=earliest
mp.messaging.incoming.motion-event-in.failure-strategy=fail
